/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.glasswindow.jobsearch;

import java.time.LocalDate;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
    System.out.println("Hello from Spring..");
    System.out.println(LocalDate.now());
  }
}
